[virtual box]
startup  = vboxmanage startvm "Oracle DB Developer VM"
shutdown = vboxmanage controlvm "Oracle DB Developer VM" shutdown

[schema updater]
virtualbox m1    = cd C:\Dev\m1\core\scaffolder\data\output\Emergensys.ORA_SchemaUpdater  & sqlplus multiservices/panoramix@virtualbox @__run-standard-fr.sql
virtualbox m2    = cd C:\Dev\m2\core\scaffolder\data\output\Emergensys.ORA_SchemaUpdater  & sqlplus multiservices/panoramix@virtualbox @__run-standard-fr.sql
tes_ra@levis.dev = cd C:\Dev\m1\core\scaffolder\data\output\Emergensys.ORA_SchemaUpdater  & tes_ra/panoramix@levis.dev @__run-levis.sql

[scaffolder refactoring]
remaster1       = rmdir /Q /S C:\Users\ab112744\Desktop\master_output & mkdir C:\Users\ab112744\Desktop\master_output & xcopy C:\Dev\m1\core\scaffolder\data\output\*.*  C:\Users\ab112744\Desktop\master_output /s/y/i/q
compare output1 = start meld C:\Users\ab112744\Desktop\master_output C:\Dev\m1\core\scaffolder\data\output

remaster2       = rmdir /Q /S C:\Users\ab112744\Desktop\master_output & mkdir C:\Users\ab112744\Desktop\master_output & xcopy C:\Dev\m2\core\scaffolder\data\output\*.*  C:\Users\ab112744\Desktop\master_output /s/y/i/q
compare output2 = start meld C:\Users\ab112744\Desktop\master_output C:\Dev\m2\core\scaffolder\data\output

remaster3       = rmdir /Q /S C:\Users\ab112744\Desktop\master_output & mkdir C:\Users\ab112744\Desktop\master_output & xcopy C:\Dev\m3\core\scaffolder\data\output\*.*  C:\Users\ab112744\Desktop\master_output /s/y/i/q
compare output3 = start meld C:\Users\ab112744\Desktop\master_output C:\Dev\m3\core\scaffolder\data\output

[compare m2 vs m1]
everything  = start meld c:\dev\m2 c:\dev\m1
scaffolder  = start meld C:\Dev\m2\core\scaffolder C:\Dev\m1\core\scaffolder

[custom compare]
geoloc = start meld C:\dev\m2\geolocation\Emergensys.Geolocation.Service C:\dev\m1\geolocation\Emergensys.Geolocation.Service

[ini editor]
m1 = msbuild C:\dev\m1\tools\IniEditor\IniEditor.sln & start C:\dev\m1\tools\IniEditor\bin\Debug\IniEditor.exe
m2 = msbuild C:\dev\m2\tools\IniEditor\IniEditor.sln & start C:\dev\m2\tools\IniEditor\bin\Debug\IniEditor.exe

[misc]
mounts home directory = net use h: \\100.79.20.83\home /user:alain
git cleanup           = git clean -xdf
disk space analysis   = start SpaceSniffer
deploy ReleaseNotesGenerator = copy "C:\dev\m1\ai-automation\Emergensys.ReleaseNotes\bin\Debug\net10.0\*.*" "C:\My\bin\ReleaseNotesGenerator"
deploy MapReduce = copy "C:\dev\m1\ai-automation\Emergensys.MatchaCrawler\bin\Debug\net8.0\*.*" "C:\My\bin\MapReduce"

install geolocation service = sc create "Emergensys.Geolocation.Service" binPath= "C:\dev\m1\geolocation\Emergensys.Geolocation.Service\bin\Release\net8.0\Emergensys.Geolocation.Service.exe" start= auto DisplayName= "Emergensys Geolocation Service"
remove geolocation service  = sc delete "Emergensys.Geolocation.Service"

; Recent history (auto-generated)
; pick:recent:v2:1772581507|ini editor|m2
